version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data

  db:
    image: postgres:latest
    container_name: bousim-db
    environment:
      - POSTGRES_USER=bousim
      - POSTGRES_PASSWORD=bousim
      - POSTGRES_DB=bousim
    ports:
      - "5432:5432"
    volumes:
      - bousim_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  bousim_data:
